# -*- coding: utf-8 -*-
"""hotel_management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wc-xlkgLbBB0txCPYOvG6LQrQewLK5uN
"""

import mysql.connector

# Establish connection to the MySQL database
def connect_db():
    return mysql.connector.connect(
        host='localhost',
        user='root',
        passwd='',
        database='' #enter your database name
    )

# Function to insert new hotel booking records
def add():
    mydb = None
    mycur = None
    try:
        mydb = connect_db()
        mycur = mydb.cursor()
        x = int(input("Enter number of records to add: "))

        for _ in range(x):
            cno = int(input("Customer number: "))
            cname = input("Customer name: ")
            address = input("Address: ")
            roomno = int(input("Room number: "))
            mobileno = int(input("Mobile number: "))
            check_in = input("Check-in date (YYYY-MM-DD): ")
            check_out = input("Check-out date (YYYY-MM-DD): ")
            adv_pay = float(input("Advance payment: "))
            roomtype = int(input("Room category (1: duplex, 2: semi-duplex, 3: standard): "))

            # Map numeric input to room category string
            room_type = {1: 'duplex', 2: 'semi-duplex', 3: 'standard'}.get(roomtype)
            if not room_type:
                print("Invalid room category selected. Skipping entry.")
                continue

            query = """INSERT INTO hotel
                       (cno, cname, address, roomno, mobileno, check_in, check_out, adv_pay, room_type)
                       VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)"""
            values = (cno, cname, address, roomno, mobileno, check_in, check_out, adv_pay, room_type)

            mycur.execute(query, values)
            mydb.commit()
            print("Record added successfully.")

    except Exception as e:
        print(f"Error adding record: {e}")
    finally:
        # Ensure database cursor and connection are closed
        if mycur:
            mycur.close()
        if mydb:
            mydb.close()

# Function to search and display a single record by customer number
def display():
    mydb = None
    mycur = None
    try:
        mydb = connect_db()
        mycur = mydb.cursor()
        cno = int(input("Enter customer number: "))

        mycur.execute("SELECT * FROM hotel WHERE cno = %s", (cno,))
        myrec = mycur.fetchall()

        if not myrec:
            print("No record found with that customer number.")
        else:
            for record in myrec:
                print(*record, sep=" | ")

    except Exception as e:
        print(f"Error displaying record: {e}")
    finally:
        if mycur:
            mycur.close()
        if mydb:
            mydb.close()

# Function to calculate stay duration, bill total, taxes, and net payment
def generate():
    mydb = None
    mycur = None
    try:
        mydb = connect_db()
        mycur = mydb.cursor()
        cno = int(input("Enter customer number: "))

        # SQL query calculates day difference between check-out and check-in dates directly
        mycur.execute("""SELECT cno, cname, address, roomno, mobileno, check_in, check_out, adv_pay,
                         room_type, DATEDIFF(check_out, check_in)
                         FROM hotel WHERE cno = %s""", (cno,))
        myrec = mycur.fetchall()

        if not myrec:
            print("No record found for generating bill.")
        else:
            for x in myrec:
                total = x[9] * 4500     # Calculate base stay cost (Days * Rate)
                tax = total * 0.10      # 10% tax rate
                net = total - x[7] + tax # Net bill = Base cost - Advance Payment + Tax

                print(f"{x[0]} | {x[1]} | {x[2]} | {x[3]} | {x[4]} | {x[5]} | {x[6]} | {x[8]} | Days: {x[9]} | Total: {total} | Advance: {x[7]} | Tax: {tax} | Net: {net}")

    except Exception as e:
        print(f"Error generating report: {e}")
    finally:
        if mycur:
            mycur.close()
        if mydb:
            mydb.close()

# Function to update existing record details
def edit():
    mydb = None
    mycur = None
    try:
        mydb = connect_db()
        mycur = mydb.cursor()
        cno = int(input("Enter customer number to edit: "))

        # Verify whether the record exists
        mycur.execute("SELECT * FROM hotel WHERE cno = %s", (cno,))
        existing = mycur.fetchone()
        if not existing:
            print("Customer number not found.")
            return

        print("Existing record:", existing)

        check_in = input("New check-in date (YYYY-MM-DD): ")
        check_out = input("New check-out date (YYYY-MM-DD): ")
        adv_pay = float(input("New advance payment: "))
        roomtype = int(input("Room category (1: duplex, 2: semi-duplex, 3: standard): "))
        room_type = {1: 'duplex', 2: 'semi-duplex', 3: 'standard'}.get(roomtype)

        if not room_type:
            print("Invalid room type. Edit aborted.")
            return

        query = """
            UPDATE hotel
            SET check_in = %s, check_out = %s, adv_pay = %s, room_type = %s
            WHERE cno = %s
        """
        values = (check_in, check_out, adv_pay, room_type, cno)
        mycur.execute(query, values)
        mydb.commit()

        if mycur.rowcount > 0:
            print("Record updated successfully.")
        else:
            print("No changes made to the record.")

    except Exception as e:
        print(f"Error while updating record: {e}")
    finally:
        if mycur:
            mycur.close()
        if mydb:
            mydb.close()

# Function to delete a customer record by customer number
def delete():
    mydb = None
    mycur = None
    try:
        mydb = connect_db()
        mycur = mydb.cursor()
        cno = int(input("Enter customer number to delete: "))

        mycur.execute("DELETE FROM hotel WHERE cno = %s", (cno,))
        mydb.commit()

        if mycur.rowcount > 0:
            print("Record deleted successfully.")
        else:
            print("No record found with that customer number.")

    except Exception as e:
        print(f"Error deleting record: {e}")
    finally:
        if mycur:
            mycur.close()
        if mydb:
            mydb.close()

# Function to view all database entries
def view_all():
    mydb = None
    mycur = None
    try:
        mydb = connect_db()
        mycur = mydb.cursor()
        mycur.execute("SELECT * FROM hotel")
        records = mycur.fetchall()

        if not records:
            print("No records found in database.")
        else:
            for rec in records:
                print(*rec, sep=" | ")

    except Exception as e:
        print(f"Error fetching records: {e}")
    finally:
        if mycur:
            mycur.close()
        if mydb:
            mydb.close()

# Main menu driver function
def main():
    while True:
        print("\n\tMAIN MENU")
        print("1. Add New Record")
        print("2. Search a Record")
        print("3. Update the Record")
        print("4. Delete the Record")
        print("5. View All Records")
        print("6. Generate Report")
        print("0. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            add()
        elif choice == '2':
            display()
        elif choice == '3':
            edit()
        elif choice == '4':
            delete()
        elif choice == '5':
            view_all()
        elif choice == '6':
            generate()
        elif choice == '0':
            print("Exiting application. Goodbye!")
            break
        else:
            print("Invalid choice. Please select from 0 to 6.")

# Program execution entry point
if __name__ == "__main__":
    # Install the mysql.connector library if not already installed
    try:
        import mysql.connector
    except ImportError:
        print("Installing mysql-connector-python...")
        !pip install mysql-connector-python
        print("Installation complete. Please re-run the cell.")
        exit() # Exit to allow the user to re-run the cell after installation

    main()